#dispatch-kubernetes configmap
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "common.names.fullname" . }}-dispatch-kubernetes
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: dispatch-kubernetes
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
data:
  application.yml: |-
    {{- include "bkci.dispatch-kubernetes.yaml" . | nindent 4 -}}
