# 初始化iam
{{ if eq .Values.config.bkCiAuthProvider "bk_login_v3" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.names.fullname" . }}-init-iam
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: init-iam
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: init-iam
    spec:
      {{- if .Values.mysql.enabled }}
      initContainers:
        - name: wait-for-mysql
          image: {{ include "common.images.image" ( dict "imageRoot" .Values.backendImage "global" .Values.global) }}
          imagePullPolicy: {{ .Values.backendImage.pullPolicy }}
          command:
            - "/bin/sh"
            - "-c"
            - |
              until getent hosts {{ include "bkci.mysql.fullname" . }}
              do 
                echo waiting for {{ include "bkci.mysql.fullname" . }};
                sleep 2;
              done
              echo "MySQL is available";
      {{- end }}
      containers:
        - name: init-iam
          image: {{ include "common.images.image" ( dict "imageRoot" .Values.backendImage "global" $) }}
          imagePullPolicy: {{ .Values.backendImage.pullPolicy }}
          workingDir: /data/workspace/support-files/bkiam
          {{ $mysqlData := split ":" (include "bkci.mysqlAddr" .) }}
          command:
            - "/bin/bash"
            - "-c"
            - |
              # 准备环境
              yum install -y epel-release;
              yum install -y python3;
              pip3 install requests;
              # 修改auth链接
              sed -i 's/ci-auth.service.consul:21936/{{- .Values.config.bkCiHost -}}\/auth/g' *.json
              # 导入模型
              python3 bkiam_do_migrate.py -t {{ .Values.config.bkIamPrivateUrl }} -a "{{ .Values.config.bkCiAppCode }}" -s "{{ .Values.config.bkCiAppToken }}" -f  0003_bk_ci_20200623-2120_iam.json
              python3 bkiam_do_migrate.py -t {{ .Values.config.bkIamPrivateUrl }} -a "{{ .Values.config.bkCiAppCode }}" -s "{{ .Values.config.bkCiAppToken }}" -f  0004_bk_ci_20200623-2120_iam.json
              python3 bkiam_do_migrate.py -t {{ .Values.config.bkIamPrivateUrl }} -a "{{ .Values.config.bkCiAppCode }}" -s "{{ .Values.config.bkCiAppToken }}" -f  0005_bk_ci_20200623-2120_iam.json
              python3 bkiam_do_migrate.py -t {{ .Values.config.bkIamPrivateUrl }} -a "{{ .Values.config.bkCiAppCode }}" -s "{{ .Values.config.bkCiAppToken }}" -f  0006_bk_ci_20200623-2120_iam.json
              python3 bkiam_do_migrate.py -t {{ .Values.config.bkIamPrivateUrl }} -a "{{ .Values.config.bkCiAppCode }}" -s "{{ .Values.config.bkCiAppToken }}" -f  0007_bk_ci_20200804-1047_iam.json
              # 导入数据库
              cat << EOF > iam.sql
              INSERT INTO T_AUTH_IAM_CALLBACK (GATEWAY,PATH, RESOURCE,SYSTEM) VALUES ("{{- .Values.config.bkCiPublicUrl -}}", "/ms/process/api/open/pipeline/callback/", "pipeline", "ci");
              INSERT INTO T_AUTH_IAM_CALLBACK (GATEWAY,PATH, RESOURCE,SYSTEM) VALUES ("{{- .Values.config.bkCiPublicUrl -}}", "/ms/repository/api/open/repository/callback/", "repertory", "ci");
              INSERT INTO T_AUTH_IAM_CALLBACK (GATEWAY,PATH, RESOURCE,SYSTEM) VALUES ("{{- .Values.config.bkCiPublicUrl -}}", "/ms/ticket/api/open/ticket/callback/credential/", "credential", "ci");
              INSERT INTO T_AUTH_IAM_CALLBACK (GATEWAY,PATH, RESOURCE,SYSTEM) VALUES ("{{- .Values.config.bkCiPublicUrl -}}", "/ms/ticket/api/open/ticket/callback/cert/", "cert", "ci");
              INSERT INTO T_AUTH_IAM_CALLBACK (GATEWAY,PATH, RESOURCE,SYSTEM) VALUES ("{{- .Values.config.bkCiPublicUrl -}}", "/ms/environment/api/open/environment/callback/env/", "environment", "ci");
              INSERT INTO T_AUTH_IAM_CALLBACK (GATEWAY,PATH, RESOURCE,SYSTEM) VALUES ("{{- .Values.config.bkCiPublicUrl -}}", "/ms/environment/api/open/environment/callback/node/", "env_node", "ci");
              INSERT INTO T_AUTH_IAM_CALLBACK (GATEWAY,PATH, RESOURCE,SYSTEM) VALUES ("{{- .Values.config.bkCiPublicUrl -}}", "/ms/quality/api/open/quality/callback/rule", "rule", "ci");
              INSERT INTO T_AUTH_IAM_CALLBACK (GATEWAY,PATH, RESOURCE,SYSTEM) VALUES ("{{- .Values.config.bkCiPublicUrl -}}", "/ms/quality/api/open/quality/callback/group", "quality_group", "ci");
              INSERT INTO T_AUTH_IAM_CALLBACK (GATEWAY,PATH, RESOURCE,SYSTEM) VALUES ("{{- .Values.config.bkCiPublicUrl -}}", "/ms/experience/api/open/experience/callback/task", "experience_task", "ci");
              INSERT INTO T_AUTH_IAM_CALLBACK (GATEWAY,PATH, RESOURCE,SYSTEM) VALUES ("{{- .Values.config.bkCiPublicUrl -}}", "/ms/experience/api/open/experience/callback/group", "experience_group", "ci");
              INSERT INTO T_AUTH_IAM_CALLBACK (GATEWAY,PATH, RESOURCE,SYSTEM) VALUES ("{{- .Values.config.bkCiPublicUrl -}}", "/ms/project/api/open/project/callback/", "project", "ci");
              EOF
              mysql -u{{- include "bkci.mysqlUsername" . }} -p{{- include "bkci.mysqlPassword" . }} -h{{ $mysqlData._0 }} -P{{ $mysqlData._1 }} devops_ci_auth < iam.sql;
      restartPolicy: OnFailure
{{ end }}
