#notify Deployment
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}-notify
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: microservice
    app.kubernetes.io/name: notify
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: microservice
      app.kubernetes.io/name: notify
  replicas: {{ .Values.notify.replicas }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        {{- if .Values.notify.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.notify.podLabels "context" $) | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: microservice
        app.kubernetes.io/name: notify
    spec:
      serviceAccountName: {{ .Values.rbac.serviceAccount }}
      {{- if .Values.notify.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.notify.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.notify.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.notify.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.notify.podAffinityPreset "component" "notify" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.notify.podAntiAffinityPreset "component" "notify" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.notify.nodeAffinityPreset.type "key" .Values.notify.nodeAffinityPreset.key "values" .Values.notify.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.notify.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.notify.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.notify.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.notify.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.notify.priorityClassName }}
      priorityClassName: {{ .Values.notify.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.notify.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.notify.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}        
      containers:
        - name: notify
          image: {{ include "common.images.image" ( dict "imageRoot" .Values.backendImage "global" $) }}
          imagePullPolicy: {{ .Values.backendImage.pullPolicy }}
          {{- if .Values.notify.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.notify.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.notify.resources }}
          resources: {{- toYaml .Values.notify.resources | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
          env:
            - name: MS_NAME
              value: notify
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: SERVICE_PREFIX
              value: {{ include "common.names.fullname" . }}
            - name: JVM_XMS
              value: {{ .Values.notify.env.JVM_XMS }}
            - name: JVM_XMX
              value: {{ .Values.notify.env.JVM_XMX }}
          workingDir: /data/workspace/notify
          command:
            - "/bin/bash"
            - "-c"
            - |
              cp /data/workspace/backend.bkci.sh .;
              /bin/bash backend.bkci.sh;
          livenessProbe:
            httpGet:
              path: /management/health/livenessState
              port: http
            initialDelaySeconds: 90
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 5
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /management/health/readinessState
              port: http
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 5
            successThreshold: 1
