{{- if .Values.schedule.enabled -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "common.names.fullname" . }}-schedule
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: schedule
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
data:
  application.yml: |-
    spring:
      application:
        name: schedule
        desc: schedule Service
        packageName: com.tencent.bk.codecc.defect
      data:
        mongodb:
          uri: {{ include "codecc.defect.mongodbUri" . }}
    codecc:
      gateway:
        host: {{ .Values.config.BK_CODECC_PUBLIC_URL }}
      file:
        data:
          path: {{ .Values.config.BK_CODECC_FILE_DATA_PATH }}
    result:
      log:
        path: /data/woskspace/logs
    {{- if keys $.Values.schedule.config }}
      {{- toYaml .Values.schedule.config | nindent 4 }}
    {{- end}}
{{- end }}
