{{- if .Values.asyncreport.enabled -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "common.names.fullname" . }}-asyncreport
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: asyncreport
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
data:
  application.yml: |-
    spring:
      application:
        name: asyncreport
        desc: AsyncReport Service
        packageName: com.tencent.bk.codecc.defect
      data:
        mongodb:
          uri: {{ include "codecc.defect.mongodbUri" . }}
    devopsGateway:
      idchost: {{ .Values.config.BK_CI_PUBLIC_URL }}
    codecc:
      gateway:
        host: {{ .Values.config.BK_CODECC_PUBLIC_URL }}
    {{- if keys $.Values.asyncreport.config }}
      {{- toYaml .Values.asyncreport.config | nindent 4 }}
    {{- end}}
{{- end }}
