kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-plugin-zhiyan-log
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
data:
  client.lua: |- {{ .Files.Get "plugins/zhiyan-log/client.lua" | nindent 4 }}
  msgpack.lua: |- {{ .Files.Get "plugins/zhiyan-log/msgpack.lua" | nindent 4 }}