{{- if .Values.bkmonitor.collectEnabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "common.names.fullname" . }}-bkmonitor
spec:
  endpoints:
    - interval: 30s # 采集周期
      path: /management/prometheus # 指标接口路径
      port: http # service的端口名，必须使用端口名，不能使用数字
  namespaceSelector:
    any: true
  selector: # 过滤出需要采集的service
    matchLabels: {{- include "common.labels.standard" . | nindent 4 }}
      {{- if .Values.commonLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
      {{- end }}
      app.kubernetes.io/component: microservice
{{- end }}
